const jwt=require('jsonwebtoken');
const Provider=require('../../models/Provider');
const {normalizeMobile}=require('../../utils/mobile');

async function findProvider(mobileInput){const mobile=normalizeMobile(mobileInput);if(mobile.length!==10)return null;const list=await Provider.find({$or:[{normalizedMobile:mobile},{mobile}]}).limit(10).lean();return list.find(p=>String(p.status).toLowerCase()==='active'&&p.portalAccessEnabled!==false)||list[0]||null;}
function assertEligible(provider){if(!provider)throw Object.assign(new Error('No provider account matches this mobile number'),{status:404});if(String(provider.status).toLowerCase()!=='active')throw Object.assign(new Error(`Provider account is ${provider.status||'inactive'}`),{status:403});if(provider.portalAccessEnabled===false)throw Object.assign(new Error('Provider portal access is disabled in CRM'),{status:403});return provider;}
async function sendOtp(mobileInput){const mobile=normalizeMobile(mobileInput);if(mobile.length!==10)throw Object.assign(new Error('Enter a valid 10-digit mobile number'),{status:400});const provider=assertEligible(await findProvider(mobile));if(process.env.OTP_API_URL){const response=await fetch(`${process.env.OTP_API_URL}${process.env.OTP_SEND_PATH||'/otp/send-otp'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile})});if(!response.ok)throw Object.assign(new Error('OTP service could not send the code'),{status:502});}return{mobile,providerId:provider.providerId||provider.id,devOtp:process.env.NODE_ENV==='production'?undefined:(process.env.DEV_OTP_CODE||'123456')};}
async function verifyOtp(mobileInput,otpInput){const mobile=normalizeMobile(mobileInput);const otp=String(otpInput||'').trim();let verified=false;if(process.env.OTP_API_URL){const response=await fetch(`${process.env.OTP_API_URL}${process.env.OTP_VERIFY_PATH||'/otp/verify-otp'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile,otp})});const body=await response.json().catch(()=>({}));verified=response.ok&&Boolean(body.success||body.verify||body.verified);}else if(process.env.NODE_ENV!=='production'){verified=otp===(process.env.DEV_OTP_CODE||'123456');}if(!verified)throw Object.assign(new Error('Invalid or expired OTP'),{status:401});const provider=assertEligible(await findProvider(mobile));const providerId=provider.providerId||provider.id||String(provider._id);await Provider.updateOne({$or:[{providerId},{id:providerId},{_id:providerId}]},{$set:{normalizedMobile:mobile,lastLoginAt:new Date(),updatedAt:new Date()}});return{...provider,providerId};}
function sign(provider){return jwt.sign({sub:provider.providerId,type:'provider'},process.env.JWT_SECRET||'change-provider-secret',{expiresIn:`${Number(process.env.AUTH_COOKIE_DAYS||30)}d`});}
module.exports={findProvider,assertEligible,sendOtp,verifyOtp,sign,normalizeMobile};
