const router = require("express").Router();
const controller = require("../controllers/agentController");
const { requirePermission } = require("../middleware/auth");
router.get("/", requirePermission("agents.view"), controller.list);
router.post("/", requirePermission("agents.create"), controller.create);
router.get("/:agentId/requirements", requirePermission("agents.view"), controller.requirements);
router.get("/:agentId", requirePermission("agents.view"), controller.get);
router.put("/:agentId", requirePermission("agents.edit"), controller.update);
router.patch("/:agentId", requirePermission("agents.edit"), controller.update);
module.exports = router;
