const router = require("express").Router();
const page = require("../controllers/frontendController");
const { pageAuth, requirePermission } = require("../middleware/auth");

const protectedPage = (permission) => [pageAuth, requirePermission(permission)];

router.get("/login", page.login);
router.get("/", (req, res) => res.redirect(req.admin ? "/dashboard" : "/login"));
router.get("/dashboard", ...protectedPage("dashboard.view"), page.dashboard);
router.get("/enquiries", ...protectedPage("requirements.view"), page.enquiries);
router.get("/requirements", ...protectedPage("requirements.view"), page.enquiries);
router.get("/enquiries/new", ...protectedPage("requirements.create"), page.enquiryCreate);
router.get("/requirements/new", ...protectedPage("requirements.create"), page.enquiryCreate);
router.get("/enquiries/:enquiryId/edit", ...protectedPage("requirements.edit"), page.enquiryEdit);
router.get("/requirements/:enquiryId/edit", ...protectedPage("requirements.edit"), page.enquiryEdit);
router.get("/enquiries/:enquiryId/providers/:leadDistributionId", ...protectedPage("requirements.view"), page.enquiryProviderStatusShow);
router.get("/requirements/:enquiryId/providers/:leadDistributionId", ...protectedPage("requirements.view"), page.enquiryProviderStatusShow);
router.get("/enquiries/:enquiryId/providers", ...protectedPage("requirements.view"), page.enquiryProviderStatuses);
router.get("/requirements/:enquiryId/providers", ...protectedPage("requirements.view"), page.enquiryProviderStatuses);
router.get("/enquiries/:enquiryId", ...protectedPage("requirements.view"), page.enquiryShow);
router.get("/requirements/:enquiryId", ...protectedPage("requirements.view"), page.enquiryShow);
router.get("/providers", ...protectedPage("providers.view"), page.providers);
router.get("/providers/new", ...protectedPage("providers.create"), page.providerCreate);
router.get("/providers/:providerId/edit", ...protectedPage("providers.edit"), page.providerEdit);
router.get("/providers/:providerId", ...protectedPage("providers.view"), page.providerShow);
router.get("/agents", ...protectedPage("agents.view"), page.agents);
router.get("/agents/new", ...protectedPage("agents.create"), page.agentCreate);
router.get("/agents/:agentId/edit", ...protectedPage("agents.edit"), page.agentEdit);
router.get("/agents/:agentId", ...protectedPage("agents.view"), page.agentShow);
router.get("/partner-withdrawals", ...protectedPage("partnerPayouts.view"), page.partnerWithdrawals);
router.get("/partner-withdrawals/:withdrawalId", ...protectedPage("partnerPayouts.view"), page.partnerWithdrawalShow);
router.get("/categories", ...protectedPage("categories.view"), page.categories);
router.get("/follow-ups", ...protectedPage("followUps.view"), page.followUps);
router.get("/follow-ups/new", ...protectedPage("followUps.create"), page.followUpCreate);
router.get("/follow-ups/:followUpId/edit", ...protectedPage("followUps.edit"), page.followUpEdit);
router.get("/communications", ...protectedPage("communications.view"), page.communications);
router.get("/communications/logs", ...protectedPage("communications.view"), page.communicationLogs);
router.get("/communications/send", ...protectedPage("communications.send"), page.communicationSend);
router.get("/communications/templates", ...protectedPage("communications.view"), page.communicationTemplates);
router.get("/communications/templates/new", ...protectedPage("communications.manage"), page.communicationTemplateCreate);
router.get("/communications/templates/:templateId/edit", ...protectedPage("communications.manage"), page.communicationTemplateEdit);
router.get("/communications/rules", ...protectedPage("communications.view"), page.communicationRules);
router.get("/communications/otp", ...protectedPage("communications.view"), page.communicationOtp);
router.get("/communications/settings", ...protectedPage("communications.manage"), page.communicationSettings);
router.get("/communications/new", ...protectedPage("communications.send"), page.communicationCreate);
router.get("/communications/:communicationId/edit", ...protectedPage("communications.manage"), page.communicationEdit);
router.get("/billing", ...protectedPage("billing.view"), page.invoices);
router.get("/billing/provider-subscriptions", ...protectedPage("billing.view"), page.providerSubscriptions);
router.get("/billing/new", ...protectedPage("billing.create"), page.invoiceCreate);
router.get("/billing/:invoiceId/edit", ...protectedPage("billing.edit"), page.invoiceEdit);
router.get("/distributions", ...protectedPage("distributions.view"), page.distributions);
router.get("/reports", ...protectedPage("reports.view"), page.reports);
router.get("/storage", ...protectedPage("storage.view"), page.storage);
router.get("/employees", ...protectedPage("employees.view"), page.employees);
router.get("/employees/new", ...protectedPage("employees.create"), page.employeeCreate);
router.get("/employees/:employeeId/edit", ...protectedPage("employees.edit"), page.employeeEdit);
router.get("/roles", ...protectedPage("roles.view"), page.roles);
router.get("/roles/new", ...protectedPage("roles.create"), page.roleCreate);
router.get("/roles/:roleId/edit", ...protectedPage("roles.edit"), page.roleEdit);
router.get("/search/enquiries", ...protectedPage("requirements.view"), page.enquiries);
router.get("/search/providers", ...protectedPage("providers.view"), page.providers);
router.get("/search/agents", ...protectedPage("agents.view"), page.agents);
router.get("/search/follow-ups", ...protectedPage("followUps.view"), page.followUps);
router.get("/search/communications", ...protectedPage("communications.view"), page.communicationLogs);
router.get("/search/invoices", ...protectedPage("billing.view"), page.invoices);

module.exports = router;
