const crypto=require('crypto');
const Razorpay=require('razorpay');
const Provider=require('../../models/Provider');
const WalletTransaction=require('../../models/WalletTransaction');
const PaymentOrder=require('../../models/PaymentOrder');
const {createId}=require('../../utils/id');
const {getPagination,pageResult}=require('../../utils/pagination');

function providerQuery(providerId){return{$or:[{providerId},{id:providerId},{_id:providerId}]};}
function razorpay(){if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)throw Object.assign(new Error('Razorpay is not configured'),{status:503});return new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET});}
async function get(providerId,filters={}){const provider=await Provider.findOne(providerQuery(providerId)).lean();if(!provider)throw Object.assign(new Error('Provider not found'),{status:404});const{page,limit,skip}=getPagination(filters);const[data,total]=await Promise.all([WalletTransaction.find({providerId}).sort({createdAt:-1}).skip(skip).limit(limit).lean(),WalletTransaction.countDocuments({providerId})]);return{provider:{...provider,providerId},...pageResult(data,total,page,limit)};}
async function credit(providerId,amountPaise,source,referenceId,idempotencyKey,metadata={}){const existing=await WalletTransaction.findOne({idempotencyKey}).lean();if(existing)return existing;const provider=await Provider.findOneAndUpdate({...providerQuery(providerId)},{$inc:{walletBalancePaise:amountPaise},$set:{walletUpdatedAt:new Date(),updatedAt:new Date()}},{new:true});if(!provider)throw Object.assign(new Error('Provider not found'),{status:404});const transaction=await WalletTransaction.create({walletTransactionId:createId('wallet_txn'),providerId,type:'credit',amountPaise,currency:'INR',balanceBeforePaise:provider.walletBalancePaise-amountPaise,balanceAfterPaise:provider.walletBalancePaise,status:'posted',source,referenceId,idempotencyKey,description:`Wallet credit ₹${amountPaise/100}`,metadata});return transaction.toObject();}
async function demoTopup(providerId,amountPaise){if(process.env.NODE_ENV==='production'&&process.env.ALLOW_DEMO_TOPUP!=='true'&&process.env.ENABLE_DEMO_WALLET_TOPUP!=='true')throw Object.assign(new Error('Demo top-up is disabled'),{status:403});const amount=Math.max(100,Number(amountPaise||0));return credit(providerId,amount,'admin',`demo-${Date.now()}`,`demo:${providerId}:${Date.now()}`,{demo:true});}
async function createOrder(providerId,amountPaise){const amount=Math.max(100,Number(amountPaise||0));const gateway=razorpay();const receipt=`wallet_${Date.now()}`;const order=await gateway.orders.create({amount,currency:'INR',receipt,notes:{providerId}});const local=await PaymentOrder.create({paymentOrderId:createId('pay_order'),providerId,gatewayOrderId:order.id,amountPaise:amount,currency:'INR',status:'created',receipt});return{keyId:process.env.RAZORPAY_KEY_ID,orderId:order.id,amountPaise:amount,currency:'INR',paymentOrderId:local.paymentOrderId};}
function validSignature(orderId,paymentId,signature){const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET||'').update(`${orderId}|${paymentId}`).digest('hex');return expected.length===String(signature||'').length&&crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(String(signature||'')));}
async function verify(providerId,input){const orderId=String(input.razorpay_order_id||input.orderId||'');const paymentId=String(input.razorpay_payment_id||input.paymentId||'');const signature=String(input.razorpay_signature||input.signature||'');if(!validSignature(orderId,paymentId,signature))throw Object.assign(new Error('Invalid Razorpay signature'),{status:400});const local=await PaymentOrder.findOne({providerId,gatewayOrderId:orderId});if(!local)throw Object.assign(new Error('Wallet order not found'),{status:404});const payment=await razorpay().payments.fetch(paymentId);if(payment.order_id!==orderId||payment.status!=='captured'||Number(payment.amount)!==Number(local.amountPaise)||payment.currency!=='INR')throw Object.assign(new Error('Payment verification failed'),{status:400});const transaction=await credit(providerId,local.amountPaise,'razorpay',orderId,`razorpay-order:${orderId}`,{paymentId});await PaymentOrder.updateOne({paymentOrderId:local.paymentOrderId},{$set:{gatewayPaymentId:paymentId,status:'paid',signatureVerified:true,walletCredited:true,walletTransactionId:transaction.walletTransactionId,paidAt:new Date(),creditedAt:new Date(),updatedAt:new Date()}});return transaction;}
async function webhook(rawBody,signature){const expected=crypto.createHmac('sha256',process.env.RAZORPAY_WEBHOOK_SECRET||'').update(rawBody).digest('hex');if(!signature||expected.length!==String(signature).length||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(String(signature))))throw Object.assign(new Error('Invalid webhook signature'),{status:400});const event=JSON.parse(rawBody.toString('utf8'));const payment=event.payload?.payment?.entity;if(!payment||!['payment.captured','order.paid'].includes(event.event))return{ignored:true};const local=await PaymentOrder.findOne({gatewayOrderId:payment.order_id});if(!local)return{ignored:true};await credit(local.providerId,local.amountPaise,'razorpay',local.gatewayOrderId,`razorpay-order:${local.gatewayOrderId}`,{paymentId:payment.id,webhook:true});await PaymentOrder.updateOne({paymentOrderId:local.paymentOrderId},{$set:{gatewayPaymentId:payment.id,status:'paid',walletCredited:true,paidAt:new Date(),creditedAt:new Date(),updatedAt:new Date()}});return{credited:true};}
module.exports={get,credit,demoTopup,createOrder,verify,webhook};
